### PR TITLE
fix: bug where only first `order` clause is applied

### LINKED ISSUE #59: Request with multiple order columns is not correct
## Steps to reproduce
1. Run code similar to:
```dart
await client
        .from('atable')
        .select()
        .order('col1')
        .order('col2')
        .execute();
```
## Actual result
The URL generated is 
```http://localhost:8003/rest/v1/atable?select=%2A&order=%22col1%22.desc.nullslast&order=%22col1%22.desc.nullslast%2C%22col2%22.desc.nullslast```
Notice that there are two `order` parameters - one with `col1` and the other with `col1` and `col2`. It seems that the second `order` is ignored when it is executed. I would guess this depends on the how the server sees the order of the `order` parameters.

## Expected result
The URL generated has just a single order parameter: 
```http://localhost:8003/rest/v1/atable?select=%2A&order=%22col1%22.desc.nullslast%2C%22col2%22.desc.nullslast```

## Workaround
Use `appendSearchParams('order', 'col1,col2')` to generate the `order` parameter. This produces:
```http://localhost:8003/rest/v1/atable?select=%2A&order=col1%2Ccol2```

I'm using postgrest 0.1.9 (with supabase 0.2.14)

### PR DESCRIPTION
**Pull request by dshukertjr**
Closes https://github.com/supabase-community/postgrest-dart/issues/59

### CODE REVIEW

File: test/transforms_test.dart [hunk 1]
```diff
@@ -23,20 +23,26 @@ void main() {
...
-    expect(
-      ((res.data as List)[2] as Map)['username'],
-      'supabot',
+      (res.data as List).map((row) => (row as Map)['status']),
+      [
+        'ONLINE',
+        'ONLINE',
+        'OFFLINE',
+        'OFFLINE',
+      ],
```
Comment (dshukertjr) [inline test/transforms_test.dart:36]: For anyone wondering why `ONLINE` comes before `OFFLINE` here like I was, `order by` of enum values in Postgres works not by alphabetical order, but in the order that they were defined by `CREATE TYPE` statement. The enum here was created like this, so `ONLINE` comes first. 

```sql
CREATE TYPE public.user_status AS ENUM ('ONLINE', 'OFFLINE');
```

File: test/transforms_test.dart [hunk 2]
```diff
@@ -23,20 +23,26 @@ void main() {
...
-      ((res.data as List)[3] as Map)['username'],
-      'dragarcia',
+      (res.data as List).map((row) => (row as Map)['username']),
+      [
+        'supabot',
+        'awailas',
+        'kiwicopple',
+        'dragarcia',
+      ],
     );
```
Comment (dshukertjr) [inline test/transforms_test.dart:46]: The values here do not seem like the correct one at first glance, because other tests are modifying the values in test table. Probably will fix the tests so that each test case will reset the table after execution in later PR.

**Review by bdlukaa — APPROVED** [review]

**Comment by dsyrstad** [comment]
@bdlukaa @dshukertjr Will there be a new version with this change published soon?
