### PR TITLE
fix: maybeSingle

### LINKED ISSUE #195: maybeSingle throws exception when no results returned
When using `maybeSingle` and no results are found the below exception is thrown.  I was under the impression if no rows were found then a null result would be returned.  Am I interpreting the documentation properly?  I noticed the unit tests in the repo only check the condition where a result is returned.

How I'm using it:
```
var userProfile = await _supabaseClient!.from("user_profiles").select().eq('id', id).maybeSingle();
```

Exception:
```
PostgrestException (PostgrestException(message: {"message":"JSON object requested, multiple (or no) rows returned","details":"Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row"}, code: 406, details: Not Acceptable, hint: null))
```

### PR DESCRIPTION
**Pull request by Vinzent03**
There were multiple problems:
1. Parsing of the error failed, because `hint` was missing
2. `data` was not null, but an empty string?
3. On null it returned a `PostgrestResponse` instead of `data` directly, because `count`  was not null.

fix supabase-community/supabase-flutter/issues/195

### CODE REVIEW

**Comment by Vinzent03** [comment]
I only have flutter channel beta and stable installed. Looks like the formatter changes in the latest dart release.

File: lib/src/types.dart [hunk 1]
```diff
@@ -23,9 +23,9 @@ class PostgrestException implements Exception {
   }) {
     return PostgrestException(
       message: (json['message'] ?? message) as String,
-      code: (json['code'] ?? '$code') as String,
+      code: '$code',
```
Comment (Vinzent03) [inline lib/src/types.dart]: I'm removing `json['code']`, because on select on a not existent table, the code in the body is `42p01`. This is different from the [test](https://github.com/Vinzent03/postgrest-dart/blob/79482a6895f9e263ed034dec01c4c7b570a55b80/test/basic_test.dart#L195). So I'm changing to only use the REST status code. (https://bobcares.com/blog/postgresql-error-42p01/)

If you want to, we can change to use `42p01` instead.

Comment (bdlukaa) [reply lib/src/types.dart]: I believe it's better we use the postgrest code, instead of the rest status code. It's easier to know the issue with the postgrest code

File: .github/workflows/main.yml [hunk 2]
```diff
@@ -10,6 +10,7 @@ jobs:
   test:
     name: Test / OS ${{ matrix.os }} / Node ${{ matrix.node }} / SDK ${{ matrix.sdk }}
     strategy:
+      fail-fast: false
```
Comment (dshukertjr) [inline .github/workflows/main.yml:13]: Please enlighten me here, but why was this added?

File: test/transforms_test.dart [hunk 3]
```diff
@@ -218,13 +218,34 @@ void main() {
...
+    });
+
+    test('maybeSingle with 0 rows', () async {
+      final Map<String, dynamic>? user = await postgrest
+          .from('users')
+          .select()
+          .eq('username', 'xxxxx')
+          .maybeSingle();
+      expect(user, isNull);
+    });
```
Comment (dshukertjr) [inline test/transforms_test.dart:249]: Love these new tests 🎉

File: test/basic_test.dart [hunk 4]
```diff
@@ -200,7 +200,7 @@ void main() {
           },
           onError: (error) {
             expect(error, isA<PostgrestException>());
-            expect(error.code, '404');
+            expect(error.code, '42P01');
```
Comment (dshukertjr) [inline test/basic_test.dart:203]: Also just a simple question, but why did the error code change here?

**Review by dshukertjr — COMMENTED** [review]
@Vinzent03 Sorry for taking my time to review this one! 

Thank you so much for the quick fix here! I just had few small questions, but it all looks amazing!

File: test/basic_test.dart (hunk 4 above)
Comment (Vinzent03) [reply test/basic_test.dart:203]: Previously the parsing failed on error [here](https://github.com/supabase-community/postgrest-dart/blob/master/lib/src/postgrest_builder.dart#L225), because hint was missing. So the exception got generated [here](https://github.com/supabase-community/postgrest-dart/blob/master/lib/src/postgrest_builder.dart#L236) instead, which doesn't use the body for code generation.

File: .github/workflows/main.yml (hunk 2 above)
Comment (Vinzent03) [reply .github/workflows/main.yml:13]: The test failed only on Dart dev, because of formatting, but I don't have the Dart dev version installed. Now it doesn't abort the tests on other channels, when one channel fails.

Comment (dshukertjr) [reply .github/workflows/main.yml:13]: Ah, nice! I wasn't aware of this flag, but it feels like we should have it for all the libraries huh?

Comment (Vinzent03) [reply .github/workflows/main.yml:13]: I think so. It's easier to track why it fails on server, but not locally.

File: test/basic_test.dart (hunk 4 above)
Comment (dshukertjr) [reply test/basic_test.dart:203]: @Vinzent03 Sorry, the `here` link took me to the top of the page like the following. Where was it?
Screen Shot 2022-08-24 at 18 09 29

Comment (Vinzent03) [reply test/basic_test.dart:203]: Fixed

Comment (dshukertjr) [reply test/basic_test.dart:203]: Amazing! Thanks for the clarification! I'm just noticing the fact that Postgrest uses an interesting error code huh? 😂
https://postgrest.org/en/latest/errors.html

**Review by dshukertjr — APPROVED** [review]
Looks amazing to me! Looks like the failing tests is just the formatting rule changing in dev branch of dart, so let's merge it in!

Could we update the package version number, changelog, and version.dart as well?

**Comment by Vinzent03** [comment]
@dshukertjr I will fix supabase-community/supabase-flutter/issues/201 today as well, so please wait with release.

**Comment by dshukertjr** [comment]
Cool, merging this one then!
